[workspace]

members = [
    "serde_fix",
    "fix_common",
    "fixt11",
    "fix50sp2",
    "fix50sp1",
    "fix50",
    "fix44",
    "fix43",
    "fix42",
    "fix41",
    "fix40",
    "fix_message",
]
exclude = [
    "code_generator",
    "enum_checker",
]
